INSERT INTO tb_customers(name, address, email, notelp) VALUES('Alexa Alexander', 'Jl. in aja dulu', 'alexa@example.com', '02111111');
INSERT INTO tb_customers(name, address, email, notelp) VALUES('John Chena', 'Jl. nya sama aku, nikahnya sama dia', 'john@example.com', '02156122');
INSERT INTO tb_customers(name, address, email, notelp) VALUES('Ria Jadi Dengki', 'Jl. mulu, naik mobil kek', 'ria@example.com', '02131133');
INSERT INTO tb_customers(name, address, email, notelp) VALUES('Rudi Tambal Ban', 'Jl. nya becek, gak ada ojek', 'rudi@example.com', '02141844');
INSERT INTO tb_customers(name, address, email, notelp) VALUES('Tasya Anastasya', 'Jl. jalan kepuncak gunung, tinggi-tinggi sekali', 'tasya@example.com', '02151955');
INSERT INTO tb_customers(name, address, email, notelp) VALUES('Asep Konter', 'Jl. makmur sentosa', 'asep@example.com', '02116066');
INSERT INTO tb_customers(name, address, email, notelp) VALUES('Tono dan Tini', 'Jl. ini mengingatkannya tentang dia', 'tono@example.com', '02112177');
INSERT INTO tb_customers(name, address, email, notelp) VALUES('Rara Atasya', 'Jl. ini mengingatkannya tentang dia', 'rara@example.com', '02131077');
INSERT INTO tb_customers(name, address, email, notelp) VALUES('Jaspal Singh', 'Jl. nya becek, gak ada ojek', 'rudi@example.com', '02141844');
INSERT INTO tb_customers(name, address, email, notelp) VALUES('Rudi Tambal Ban', 'Jl. nya becek, gak ada ojek', 'rudi@example.com', '02141844');
INSERT INTO tb_customers(name, address, email, notelp) VALUES('Nantu Chandra Laha', 'Jl. nya becek, gak ada ojek', 'rudi@example.com', '02141844');
INSERT INTO tb_customers(name, address, email, notelp) VALUES('Sonu', 'Jl. nya becek, gak ada ojek', 'rudi@example.com', '02141844');
INSERT INTO tb_customers(name, address, email, notelp) VALUES('SUNITA MISHRA', 'Jl. nya becek, gak ada ojek', 'rudi@example.com', '02141844');
INSERT INTO tb_customers(name, address, email, notelp) VALUES('atsino', 'Jl. nya becek, gak ada ojek', 'atsino@example.com', '02147044');
INSERT INTO tb_customers(name, address, email, notelp) VALUES('Firoj', 'Jl. nya becek, gak ada ojek', 'firoj@example.com', '021411244');
INSERT INTO tb_customers(name, address, email, notelp) VALUES('Dia', 'Jl. nya becek, gak ada ojek', 'dia@example.com', '02132144');
INSERT INTO tb_customers(name, address, email, notelp) VALUES('Dadang Tur', 'Jl. nya becek, gak ada ojek', 'dadang@example.com', '02141244');
INSERT INTO tb_customers(name, address, email, notelp) VALUES('Mutsiko R', 'Jl. nya becek, gak ada ojek', 'mutsiko@example.com', '02145434');
INSERT INTO tb_customers(name, address, email, notelp) VALUES('Tal', 'Jl. nya becek, gak ada ojek', 'tal@example.com', '02121344');
INSERT INTO tb_customers(name, address, email, notelp) VALUES('Kane K', 'Jl. nya becek, gak ada ojek', 'kane@example.com', '02143244');
INSERT INTO tb_customers(name, address, email, notelp) VALUES('Lia Laite', 'Jl. nya becek, gak ada ojek', 'lia@example.com', '02141844');
INSERT INTO tb_customers(name, address, email, notelp) VALUES('Cofti Pore', 'Jl. nya becek, gak ada ojek', 'cofti@example.com', '02161844');
INSERT INTO tb_customers(name, address, email, notelp) VALUES('Khan Ck', 'Jl. nya becek, gak ada ojek', 'khan@example.com', '02123844');
INSERT INTO tb_customers(name, address, email, notelp) VALUES('Lole Rews', 'Jl. nya becek, gak ada ojek', 'lole@example.com', '02541844');
INSERT INTO tb_customers(name, address, email, notelp) VALUES('Retsu R', 'Jl. nya becek, gak ada ojek', 'retsu@example.com', '02341244');
INSERT INTO tb_customers(name, address, email, notelp) VALUES('lolo', 'Jl. nya becek, gak ada ojek', 'lolo@example.com', '02141144');
INSERT INTO tb_customers(name, address, email, notelp) VALUES('datiku Ki', 'Jl. nya becek, gak ada ojek', 'datiku@example.com', '02141744');
INSERT INTO tb_customers(name, address, email, notelp) VALUES('Preli Kita', 'Jl. nya becek, gak ada ojek', 'preli@example.com', '02141844');
INSERT INTO tb_customers(name, address, email, notelp) VALUES('Hikopy', 'Jl. nya becek, gak ada ojek', 'hikopy@example.com', '02146844');
INSERT INTO tb_customers(name, address, email, notelp) VALUES('Dono Ikut', 'Jl. nya becek, gak ada ojek', 'dono@example.com', '02145844');
